version: "2.2"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  lemmy:
    image: dessalines/lemmy:0.11.0
    ports:
      - "127.0.0.1:__PORT__LEMMY__:8536"
    restart: always
    environment:
      - RUST_LOG=error
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs
      - iframely

  lemmy-ui:
    image: dessalines/lemmy-ui:0.11.0
    ports:
      - "127.0.0.1:__PORT_UI__:1234"
    restart: always
    environment:
      - LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_EXTERNAL_HOST=localhost:__PORT__LEMMY__
      - LEMMY_HTTPS=false
    depends_on:
      - lemmy

  pictrs:
    image: asonix/pictrs:v0.2.5-r0
    ports:
      - "127.0.0.1:__PORT_PICTRS__:8080"
    user: 991:991
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always

  iframely:
    image: dogbin/iframely:latest
    ports:
      - "127.0.0.1:__PORT_IFRAMELY__:80"
    volumes:
      - ./iframely.config.local.js:/iframely/config.local.js:ro
    restart: always
    mem_limit: 100m
