#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null
then
	ynh_script_progression "Removing $app service integration..."
	yunohost service remove $app
fi
if ynh_hide_warnings yunohost service status $app-ui >/dev/null
then
	ynh_script_progression "Removing $app-ui service integration..."
	yunohost service remove $app-ui
fi
if ynh_hide_warnings yunohost service status $app-pict-rs >/dev/null
then
	ynh_script_progression "Removing $app-pict-rs service integration..."
	yunohost service remove $app-pict-rs
fi

ynh_config_remove_systemd
ynh_config_remove_systemd$app-ui
ynh_config_remove_systemd$app-pict-rs

ynh_config_remove_logrotate

ynh_config_remove_nginx

ynh_nodejs_remove

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
