#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi
if ynh_hide_warnings yunohost service status $app-ui >/dev/null; then
	yunohost service remove $app-ui
fi
if ynh_hide_warnings yunohost service status $app-pict-rs >/dev/null; then
	yunohost service remove $app-pict-rs
fi

# Remove the dedicated systemd config
ynh_config_remove_systemd
ynh_config_remove_systemd $app-ui
ynh_config_remove_systemd $app-pict-rs

# Remove the app-specific logrotate config
ynh_config_remove_logrotate

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
